> **Linguagens e Paradigmas de Programa√ß√£o - Prof. Cassio Leonardo**
> 
> **Nome**: Gustavo Neves Piedade Louzada
> 
> **Matr√≠cula**: 202107016
> 
> **Linguagem escolhida**: Rust ü¶Ä

---

### Tratamento de exce√ß√µes

Rust n√£o possui exce√ß√µes, mas divide seus erros em dois grupos: erros *recuper√°veis* e erros *irrecuper√°veis*.

Para a primeira categoria, Rust disp√µe do tipo `Result<T, E>`, e para o segundo grupo, possui o macro `panic!` que para a execu√ß√£o do programa caso um erro irrecuper√°vel ocorra.

#### Erros irrecuper√°veis com `panic!`

H√° duas maneiras de causar p√¢nico na pr√°tica: tomando uma a√ß√£o que cause p√¢nico no c√≥digo (como acessar um √≠ndice inexistente de um array) ou chamando explicitamente o macro `panic!`.

Vamos visualizar estes casos:

```rust
fn main() {
	panic!("crash and burn");
}
```

A execu√ß√£o deste programa gera a seguinte sa√≠da:

```console
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.25s
     Running `target/debug/panic`
thread 'main' panicked at src/main.rs:2:5:
crash and burn
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

E se tentarmos acessar um √≠ndice acima do limite de tamanho de um array:

```rust
fn main() {
	let v = vec![1, 2, 3];
	
	v[99];
}
```

Como tentamos acessar um endere√ßo que n√£o foi alocado pelo vetor, ao executarmos o programa, teremos o mesmo comportamento de p√¢nico do exemplo anterior:

```console
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/panic`
thread 'main' panicked at src/main.rs:4:6:
index out of bounds: the len is 3 but the index is 99
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


#### Erros recuper√°veis com `Result<T, E>`


O tipo `Result<T, E>` √© um enum definido da seguinte maneira:

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

`T` e `E` s√£o par√¢metros gen√©ricos de tipo, onde `T` representa o tipo de valor que ser√° retornado no caso de sucesso da variante `Ok`, e `E` representa o tipo de erro que ser√° retornado no caso de falha da variante `Err`.

Para identificar se o retorno de determinada fun√ß√£o foi um `Ok` ou um `Err`, utiliza-se a estrutura de controle `match`. Vejamos um exemplo para a abertura de um arquivo:

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {e:?}"),
            },
            other_error => {
                panic!("Problem opening the file: {other_error:?}");
            }
        },
    };
}
```

##### M√©todos `unwrap` e `expect`

Usar o `match` para verificar e tratar o erro funciona bem o suficiente, no entanto, pode acabar se tornando um atividade repetitiva e verbosa, dificultando a leitura do c√≥digo. Para evitar isso, o tipo `Result<T, E>` disponibiliza uma s√©rie de m√©todos auxiliares.

Entre eles, o m√©todo `unwrap` serve como atalho para, em caso de sucesso, retornar o valor esperado, e, em caso de erro, chamar o macro `panic!`:

```rust
use std::fs::File;

fn main() {
	let greeting_file = File::open("hello.txt").unwrap();
}
```

Executando este c√≥digo, em caso de erro, teremos a seguinte sa√≠da:

```console
thread 'main' panicked at src/main.rs:4:49:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Similarmente, o m√©todo `expect` apresenta o mesmo comportamento, mas nos permite definir a mensagem de erro do `panic!`, o que facilita a compreens√£o do que causou o comportamento fatal.

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")
        .expect("hello.txt should be included in this project");
}
```

Sa√≠da:

```console
thread 'main' panicked at src/main.rs:5:10:
hello.txt should be included in this project: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

